### ISSUE TITLE
Add support for csv

### ISSUE THREAD

**Issue by frazer-scully** [bitfocus/companion-module-google-sheets#16]
It would be amazing if alongside json, we could also get a csv output to use as a data source.

This way in vMix, we can use “Use first row as column names”.

**Comment by thedist** [comment]
This is now supported as of the latest Beta build 3.0.0+6006

The `spreadsheets` HTTP endpoint will now list 2 sets of URLs, one for JSON and one for CSV. They're essentially identical but the CSV URLs include `&format=csv`. Any existing data sources will continue to work just fine as JSON as that's the defualt.
