### ISSUE TITLE
Is there a way to toggle a checkbox ?

### ISSUE THREAD

**Issue by Pommesbude110** [bitfocus/companion-module-google-sheets#19]
Checkbox Toggle

I would like to toggle a Checkbox like [here](https://i.imgur.com/WN0Byzh.png) for switching sites in Valorant or other FPS Games

**Comment by thedist** [comment]
I haven't tested it, but I believe the value of the cell is True or False (you can test this by using the variable for that cell on a button and seeing what it says). Then to toggle it you would just send False if the current value is True, or vice versa.

**Comment by Pommesbude110** [comment]
Yeah, I tried it first in German, it didn't work for some reason, but it worked in English.
Thx :)
