### ISSUE TITLE
Unable to launch new window on saving new connection

### ISSUE THREAD

**Issue by kanetreble** [bitfocus/companion-module-google-sheets#21]
**Describe the bug**
Followed tutorial, on saving Client ID/Secret and Redirect URI, but on saving no new window to authorize accessing Google Sheets opens. 

**Expected behaviour**
New window opens.

Win 11, using Chrome Version 119.0.6045.200 (Official Build) (64-bit), Companion 3.0.0+6049-stable-126d27e8

**Comment by kanetreble** [comment]
Just confirming, Chrome settings allow popups and third party logins from my companion address

**Comment by Julusian** [comment]
I had a similar problem, running the module on headless linux where it crashes attempting to open the window.
Because it is stuck in a crash loop I am unable to paste in the code once I visit the url manually, as the config panel is unable to open due to the crashing

I expect a simple try/catch around the open call should suppress the error sufficiently when it fails

```
debug: Opening OAuth URL
error: node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [
    'https://accounts.google.com/o/oauth2/v2/auth?_________'
  ]
}

Node.js v18.18.1
Starting up module class: h
Sentry disabled
debug: new definitions
```

**Comment by thedist** [comment]
I'll work on a fix for this tomorrow, I hadn't considered Companion running on a device without a default browser capability. It's not a particularly elegant solution to begin with as in an ideal world this could more completely be handled within the frontend, but there's limited module control over the web ui.

**Comment by kanetreble** [comment]
> Press the `>_` button next to the connection to open the logs and see if any issues are showing up (at the very least it should show a `Opening OAuth URL` debug message).

Yep, just get the debug: Opening OAuth URL message.

> 
> The only time it doesn't attempt to open the auth page is if
> 
> 1. it already has an OAuth token stored, so just refreshes it.

Can it grab OAuth tokens from other modules? Haven't installed Sheets before? Is there a way to clear it to see?

> 2. the `OAuth Code` box in the config is filled, in which case it attempts to use that one time code to get an Access Token

Not the case

> 3. The Client ID, Client Secret, or Redirect URI, is empty

All filled as per instructions.

Any ideas?

**Comment by thedist** [comment]
In the patch I'm working on I'll have the auth URL put in the log once the client id, secret, and redirect have been filled in for those who it's not opening the browser of.

Until then, you could manually go to the auth URL `https://accounts.google.com/o/oauth2/v2/auth?client_id=***&redirect_uri=***&response_type=code&scope=https://www.googleapis.com/auth/spreadsheets&prompt=consent&access_type=offline`, make sure to replace the 2 sets of `***` with your Client ID, and Redirect URI.

Once you go to that auth page and accept, you'll be sent back to the redirect uri and can copy/paste the code param from the URL bar and paste that in to the Config and hopefully that will resolve the issue until I can get a fix out.

**Comment by thedist** [comment]
The latest beta should now catch any errors, and the URL to go to is logged if for whatever reason the default browser can't be opened.
