### ISSUE TITLE
Add ability to logout or remove existing credentials

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-google-sheets#22]
**Describe the feature**

It would be useful to have a way to force the module to forget any existing credentials. Clearing the oauth token does not appear to do this.

**Usecases**

I set this module up initially expecting to need just readonly access to a spreadsheet. The spreadsheet has read access to anyone with the link, write access to a few accounts.
Later I decided I needed write access, and so wanted to change the account it was logged in with, to avoid sharing it with the other account.
I tried clearing the oauth token field, but it remainded logged in, so I ended up deleting the connection so that I could login with the other account. This meant I needed to reconfigure my actions on the new connection too

**Comment by thedist** [comment]
Added a new config option that when toggled on will delete current Access and Refresh token
