### ISSUE TITLE
Can't get it to connect on another system

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion-module-google-sheets#23]
I am ready to embark on an upgrade of our major project. I have a Google sheet I have been working on for a while.
The main system is still on 2.4 (Ubuntu)

I started from scratch local (Windows) with the latest beta today 3.2 6579 and imported the project. No Issues, I then added the Sheets module, After figuring out the code trick, all was great and connected to my sheet. 

I went to the 2.4 main project and tried to add the sheets module. No go when adding hitting the save - no browser appeared.

I went to another Ubuntu and install the same new beta as Local.
I get a new browser every time I save and get a new code. But it never connects....
Here I am Ubuntu.
![image](https://github.com/bitfocus/companion-module-google-sheets/assets/11045430/46315e0b-489c-43c4-a465-b8e1430e7cbf)

Working local Windows:
![image](https://github.com/bitfocus/companion-module-google-sheets/assets/11045430/80a1b26c-9ab8-41b4-a99a-e782b136fdbd)

Very possible that I am missing something. I don't have to create a new ID for each machine do I?

Thanks, This is awesome BTW :-)

**Comment by stevespaw** [comment]
Update, I decided to try to reimport my 2.4 project locally and add the Sheet module, I am now in the endless loop mode locally and cannot get it to connect - same as the Ubuntu Clean install. Same error..

**Comment by thedist** [comment]
I can't assist with support on 2.4, as that is so out of date and things have changed since then. There's also been an update in the latest beta, 3.2.0+6580. which should improve the auth process a little by adding more logging which you'll see if you click the `>_` button next to the connection.

An error from exchanging the OAuth Code would usually indicate either the Client Secret is incorrect, the Code is incorrect, or the Code has already been used (they are 1 time use).

You don't need to create separate credentials on Google for each machine, you should be able to use the same client id, secret, and redirect on each of them and then have each one go through the OAuth process and get a code as that code is one time use so that can't be shared between machines. If Companion can't open your default browser for whatever reason, the URL you need to go to will be in the connections logs.

**Comment by stevespaw** [comment]
OK I got it to Connect! The redirect had the code, but the logs did not.
<img width="1108" alt="image" src="https://github.com/bitfocus/companion-module-google-sheets/assets/11045430/7b3925bf-b236-488a-a45b-1170803e4220">

**Comment by stevespaw** [comment]
A couple more questions :-) 
The "bug" icon gives me a 404
<img width="37" alt="image" src="https://github.com/bitfocus/companion-module-google-sheets/assets/11045430/8700e8d8-fe1b-43ff-86ae-03b718156944">
to here

<img width="407" alt="image" src="https://github.com/bitfocus/companion-module-google-sheets/assets/11045430/5659b4dc-40da-400a-a90e-ab346fd16a09">

So to understand, If I export my config to another instance I will need to put in a new Auth code and do the new "refresh tokens" and all of my connections should stay intact.  If I connect to a different sheet (copy of the first), all should connect?

Thanks!

**Comment by thedist** [comment]
So to explain the OAuth process,
1. A user goes to Googles Auth page and grants whatever permissions are needed.
2. Google redirects the user to the Redirect URI along with a `code` which the user copy/pastes into the connections settings (I'd love to be able to automate this, but different users may be using different redirect URLs, which may or may not comply with Googles requirements, so going to localhost is just something that should always work).
3. Once the user gives Companion this `code`, it is exchanged for an Access Token and a Refresh Token. The code is then discarded as it's one time use.
4. The Access Token and Refresh Token are then stored within the connections Config (they wont show in the settings page, but they are stored there). The Access Token is used to make API requests to Google, and when it expires the Refresh Token gets a new one.

As long as the Access Token and Refresh Token are valid, Companion should be able to indefinitely get new tokens by itself. If you export the config and use it somewhere else, if you're already up to step 4. then the tokens should be imported too and Companion should just be able to continue without needing to go through the auth process again.
