### ISSUE TITLE
Request: action to store a cell value into a Companion variable

### ISSUE THREAD

**Issue by GregoryBridgett** [bitfocus/companion-module-google-sheets#24]
**Describe the feature**
A new action to get the value of a cell in a given sheet and store it in a selectable companion variable, which may be called using a trigger on a set interval.

**Use Cases**
Dynamic data for live sports! Our games are updated online in a set format (penalties, goals, assists, etc) which can easily be scraped by the fantastic google sheets web scraping function. I'd love to be able to automatically generate overlay titling based on changes in variables.

**Comment by thedist** [comment]
All cells are already variables. Currently only A1 of each sheet is shown as an example as having potentially hundreds of thousands of cells shown in the variable list would crash Companions Web UI.

Additionally, depending on what titling software you're using you may be able to directly use the Google Sheets module as a data source as it provides all data as either JSON or CSV through HTTP endpoints and good title software can often get the data it needs from a HTTP link, which could save you needing to use triggers or anything like that.

**Comment by GregoryBridgett** [comment]
Thanks for the great response. I didn't think about an http API.
