### ISSUE TITLE
Crashes on headless linux

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-google-sheets#25]
**Describe the bug**
The module crashes when attempting to open the url when on headless linux.
It does log the url you need to navigate to, but because it crashes you aren't able to input the code

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
The module shouldn't crash if it fails to open the browser

**Screenshots**
![image](https://github.com/bitfocus/companion-module-google-sheets/assets/1327476/8a5c6061-0a3c-410f-ba69-d1e264d92324)

**System (please complete the following information):**

- Companion Version: 3.3.0+6848-main-f569d455
- Module version: 1.2.0

**Additional context**

**Comment by thedist** [comment]
Should be resolved in v1.3.0.

I've removed the dependency on `Open`, and instead of trying to spawn browser tabs from Companion I just provide a link in the config to the modules HTTP handler that'll redirect them to the OAuth page.
