### ISSUE TITLE
Can you please click the `>_` button on the Google Sheets connection and check the logs to see what errors or debug information is shown.

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-google-sheets#28]
Can you please click the `>_` button on the Google Sheets connection and check the logs to see what errors or debug information is shown.

_Originally posted by @thedist in https://github.com/bitfocus/companion-module-google-sheets/issues/27#issuecomment-2124414989_
            
yes, sure... here you have result after STOP and START of module (2x times):

![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/d40e30ef-d7b3-4b8a-997a-9f7939021adf)

Status is still same:

![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/efcd70b1-4668-4758-9b4c-1dd7a7bd5217)

![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/dbfd466c-89a9-4c44-9d28-0a949fb7c202)

**Comment by thedist** [comment]
Can you confirm the steps you're going through, as I can't replicate your issue and your logs don't show anything out of the ordinary.

With an app on the Google Console that has enabled the Sheets API, I can copy/paste the Client ID, Secret, and Redirect URI into the config, click save, go back into the config and follow the OAuth link, authorize the app and go through the steps until redirected to the redirect URI, and then copy/paste the `code` value from the URL bar into Companion and save again.

**Comment by Suenee** [comment]
I tried again to establish connection. 

![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/40589152-c9f9-4d94-9a5a-6f81e676b1d6)

I used CLEAR EXISTING OAUTH TOKES and press SAVE. After that I see status CONNECTING AUTHENTICATION. No redirection to google happend.

LOG REPORT:
![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/e330f6bb-0769-472b-89b9-02a3e0e582a2)

**Comment by thedist** [comment]
Did you follow the step by step instructions on the Companion page?

Step 4. literally tells you after to entering the credentials to click save, to go back in to the connection settings and click the link to the OAuth process.

**Comment by Suenee** [comment]
Oh, sorry, I missed this link.
Anyway it seems to me, that it does not work well. Check it please with me:
![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/b0b071de-eab8-4553-9df2-ea99cdd1f439)

It looks like the connection is fine now, but, when I created simple test:
![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/e15b5773-64ce-4f5c-b52e-e92f0a77d1e6)

It does not work:
![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/b28a868f-77f5-4af0-a5b2-2a75ecef0336)

I tried to grand access to everyone who knows link, but it does not help:
![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/4d70d468-fd5f-4493-9a3d-e71fc87b4670)

**Comment by thedist** [comment]
You need to use `Sheet!A1` notation when referencing a cell (if you hover over the `?` icon it'll show a tooltip explaining that), as Google Sheets needs to know specific sheet in the spreadsheet doc you're referencing as you could have many.

![Code_fVitAFlRzU](https://github.com/bitfocus/companion-module-google-sheets/assets/12213790/282b746f-f181-4d22-9c13-ce4c4ff934ad)

For example I have a sheet called `Controller`, so to adjust D43 I'd need to enter `Controler!D43` in the Companion actions

**Comment by Suenee** [comment]
Eureka! Thank you for support :-) 

![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/35f7526a-fd4a-4a49-9e2b-22f2418695f6)
![image](https://github.com/bitfocus/companion-module-google-sheets/assets/22023099/a9e55dfd-52bc-490d-a0b9-1fc820585c95)
