### ISSUE TITLE
Action to create new Sheet

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-google-sheets#31]
**Describe the feature**
Request an action to "Add Sheet". 

This would insert a new sheet (probably at the end of existing Sheets) within a workbook.

The name of the sheet should be able to accept/interpret variables, and we should be able to choose what workbook to select. 

**Usecases**
Add a couple of use cases for why this should be implemented and when/why to use it.

Use case is making a log sheet of markers during a show. Currently we can only Adjust cells, so it ends up writing over existing fields. 

Each time I generate a new session, I would generate a new sheet. The name of that sheet would be something like "LOG $(internal:custom_log_number)", and I'd use internal custom variables to increase the number for each new session/sheet. ie LOG 1, LOG 2, LOG 3. 

Then I could use the Adjust Cells action to write commands into that newly named Sheet using the same sheet name variable ie "LOG $(internal:custom_log_number)!A1".

**Comment by thedist** [comment]
v1.4.0 now includes `Add Sheet`, and `Duplicate Sheet`, actions. This'll be included in the next beta build some time today.
