### ISSUE TITLE
Increase/Decrease Value not working

### ISSUE THREAD

**Issue by CocoTech1861** [bitfocus/companion-module-google-sheets#33]
**Describe the bug**
Increase/Decrease cell value not working, only set.

**Expected behaviour**
The cell should increase by a value of 2, but it stays the same

**Screenshots**
![Image](https://github.com/user-attachments/assets/e4edc7b2-10f3-4788-bce2-3822742d854f)
![Image](https://github.com/user-attachments/assets/3d2e6cfa-ac68-4dbe-ac27-be054e4dc05d)

**System (please complete the following information):**

- Companion Version [3.4.2]
It worked last week, but it has not worked since I updated.

**Comment by thedist** [comment]
I can't reproduce this. Can you please click the `...` button next to the Sheets connection, and view the logs and see what might be shown there (with all log types enabled). The only thing I can suggest currently is double checking what format you've set that cell to (ie, make sure it's a number and not set to some other data type). Also what may be worth checking is trying to create a new action, and test if that works.

The last update to this module was 3.4.0, so nothing has changed in the last 2 patch versions of Companion.

**Comment by CocoTech1861** [comment]
[module-log-10_10_2024-4_49_12 PM.csv](https://github.com/user-attachments/files/17334092/module-log-10_10_2024-4_49_12.PM.csv)

**Comment by thedist** [comment]
Looks like the issue is with the sheet names including symbols, in this case `#`, which breaks the request URL to get sheet data (which is why setting a value works, but increase/decrease doesn't because it can't adjust a value if it can't retrieve the current value).

I'll roll out a fix today that should work, but may need some testing.
