### ISSUE TITLE
Stuck on 'Select Spreadsheet'

### ISSUE THREAD

**Issue by dxf** [bitfocus/companion-module-google-sheets#5]
**Describe the bug**
Trying to add an Adjust Cell button doesn't show any spreadsheets in the Select Spreadsheet list

**To Reproduce**
Steps to reproduce the behaviour:

1. Add new connection to Sheets, including all necessary details + Spreadsheet ID
2. Create new button to Adjust Cell
3. Highlight dropdown to select spreadsheet

**Expected behaviour**
My spreadsheet should appear

**Screenshots**
![Menu not working](https://invest-in.schlattco.in/i/zilge.png)
![Config](https://invest-in.schlattco.in/i/fpqz4.png)

**System (please complete the following information):**

- Companion Version 2.4.0 (2.4.0+4723-beta-c3cb02b6)

**Additional context**
I did check my file permissions - I'm the owner of the file

**Comment by thedist** [comment]
There's a missing step in the process that hasn't been updated yet, and was discovered in https://github.com/bitfocus/companion-module-google-sheets/issues/2 where you need to make sure to enable the Google Sheets API in the libary section in Google Cloud and that should resolve this issue.
