### ISSUE TITLE
Is it possible to change the built in Google Sheets variable via HTTP?

### ISSUE THREAD

**Issue by tomdevlive** [bitfocus/companion-module-google-sheets#8]
I noticed the variable Sheets creates contains a '!', to denote the Sheet. I cant add that to a url though like I can to update a normal custom variable. Here is what it looks like:

$(Google Sheets:SELLER-CTA-DB_selects!A1)

Maybe I'm doing it wrong? Or is it even possible to change that via HTTP?

**Comment by thedist** [comment]
A modules variables aren't custom variables that can be directly modified over HTTP. If you want to use the name of a Google Sheets variable in some other HTTP request you would need to URL encode the symbols.
